import hero from '@/assets/eliteoz-hero.jpg';
import villa from '@/assets/property-villa.jpg';
import penthouse from '@/assets/property-penthouse.jpg';
import estate from '@/assets/property-estate.jpg';

export { hero };
export const properties = [
  { id: 'ELZ-10001', name: 'The Solstice Residence', location: 'Lonavala, Maharashtra', price: '₹ 12.50 Cr', category: 'Residential', type: 'Villa', area: '8,400 sq.ft', beds: 5, baths: 6, image: villa, status: 'Published', views: 248, interests: 12 },
  { id: 'ELZ-10002', name: 'Altura Sky Penthouse', location: 'Worli, Mumbai', price: '₹ 28.00 Cr', category: 'Residential', type: 'Penthouse', area: '6,200 sq.ft', beds: 4, baths: 5, image: penthouse, status: 'Published', views: 186, interests: 8 },
  { id: 'ELZ-10003', name: 'Arbor House Estate', location: 'Whitefield, Bengaluru', price: '₹ 18.00 Cr', category: 'Residential', type: 'Estate', area: '11,600 sq.ft', beds: 6, baths: 7, image: estate, status: 'Pending Verification', views: 94, interests: 3 },
  { id: 'ELZ-10004', name: 'The Glass Pavilion', location: 'Alibaug, Maharashtra', price: '₹ 16.75 Cr', category: 'Investment', type: 'Villa', area: '9,100 sq.ft', beds: 5, baths: 5, image: hero, status: 'Published', views: 312, interests: 15 },
];
export const categories = ['Residential', 'Commercial', 'Land', 'Industrial', 'Hospitality', 'Investment'];
export const publicPages: Record<string, { title: string; eyebrow: string; description: string; sections: { title: string; body: string }[] }> = {
  about: { title: 'A more considered way to move.', eyebrow: 'ABOUT ELITEOZ', description: 'Eliteoz brings clarity, discretion and confidence to high-value real estate.', sections: [{ title: 'Built around trust', body: 'A curated marketplace designed to bring serious buyers and verified sellers together through a thoughtful, private experience.' }, { title: 'A higher standard', body: 'Identity, property information and membership are reviewed as part of the Eliteoz journey. Verification status is presented clearly at every step.' }] },
  'how-it-works': { title: 'A clear path to what’s next.', eyebrow: 'THE PROCESS', description: 'A considered experience from membership to meaningful connections.', sections: [{ title: '01 / Become a member', body: 'Choose a buyer or seller account and complete your personal information.' }, { title: '02 / Complete verification', body: 'Submit your information for review and follow your progress in your private workspace.' }, { title: '03 / Move with confidence', body: 'Explore verified opportunities or manage your listings, interests and viewing requests.' }] },
  buyers: { title: 'Exceptional places. A better way to find them.', eyebrow: 'FOR BUYERS', description: 'Discover a considered collection of high-value properties with clarity at every step.', sections: [{ title: 'Curated discovery', body: 'Search, save and compare opportunities suited to your ambitions.' }, { title: 'Private by design', body: 'Your interests and viewing requests stay organized in your own dedicated workspace.' }] },
  sellers: { title: 'Your property deserves the right audience.', eyebrow: 'FOR SELLERS', description: 'Present your property with confidence on a verification-led marketplace.', sections: [{ title: 'An elevated presentation', body: 'Create a complete listing with imagery, details and supporting documents.' }, { title: 'Manage every opportunity', body: 'Track property review, buyer interests, viewing requests and performance from one place.' }] },
  faq: { title: 'Questions, answered.', eyebrow: 'FREQUENTLY ASKED', description: 'A few things worth knowing before you begin.', sections: [{ title: 'Who can join Eliteoz?', body: 'Buyers and sellers can create an account and complete the required identity and membership steps.' }, { title: 'What does verification mean?', body: 'Eliteoz reviews submitted information and documents before marking an account or property as verified.' }, { title: 'Is my documentation visible to buyers?', body: 'No. Confidential KYC, bank and ownership documents are reserved for authorized review only.' }, { title: 'What is the activation fee?', body: 'The specification lists a ₹50,000 activation fee for buyers and sellers. Payment integration is not connected in this preview.' }] },
  contact: { title: 'Let’s start a conversation.', eyebrow: 'CONTACT', description: 'Questions about membership, a property or your account? Reach out to the Eliteoz team.', sections: [{ title: 'Membership enquiries', body: 'Use the enquiry form to tell us what you need. This frontend preview does not send messages yet.' }] },
  terms: { title: 'Terms & Conditions', eyebrow: 'POLICIES', description: 'Important information for using the Eliteoz platform.', sections: [{ title: 'Policy pending review', body: 'The final legal terms must be provided and approved by Eliteoz before launch. This page is a content placeholder, not legal advice.' }] },
  privacy: { title: 'Privacy Policy', eyebrow: 'POLICIES', description: 'How privacy is represented throughout the Eliteoz experience.', sections: [{ title: 'Private by design', body: 'Personal, identity and payment information is never shown in public property views. Final legal policy content must be supplied before launch.' }] },
  'payment-policy': { title: 'Payment Policy', eyebrow: 'POLICIES', description: 'Understand the membership activation journey.', sections: [{ title: 'Activation', body: 'The specified activation amount is ₹50,000. Gateway processing, refunds and legally binding payment terms require an approved integration and final policy text.' }] },
  'verification-policy': { title: 'Verification Policy', eyebrow: 'POLICIES', description: 'A transparent view of the verification process.', sections: [{ title: 'Review process', body: 'Submitted identity and property information is reviewed before an account or listing receives verified status. Final policy wording is pending approval.' }] },
  'seller-guidelines': { title: 'Seller Guidelines', eyebrow: 'RESOURCES', description: 'Present your property with accuracy and care.', sections: [{ title: 'A complete listing', body: 'Provide accurate specifications, clear imagery and the requested ownership information for authorized review.' }] },
  'buyer-guidelines': { title: 'Buyer Guidelines', eyebrow: 'RESOURCES', description: 'Explore opportunities thoughtfully.', sections: [{ title: 'A considered approach', body: 'Complete membership and verification, compare opportunities and use the interest and viewing tools to move forward.' }] },
};
