import hero from '@/assets/eliteoz-hero.jpg';
import villa from '@/assets/property-villa.jpg';
import penthouse from '@/assets/property-penthouse.jpg';
import estate from '@/assets/property-estate.jpg';

export { hero };
export const propertyImages: Record<string, string> = { villa, penthouse, estate, hero };
export const imageKeys = ['villa','penthouse','estate','hero'] as const;
export type Listing = { id: string; uuid: string; name: string; location: string; price: string; priceValue: number; category: string; type: string; area: string; areaValue: number; beds: number; baths: number; image: string; gallery: string[]; description: string; amenities: string[]; featured: boolean; status: string; market: string; country: string; countryCode: string; currency: string; priceInr: number | null; city: string; region: string };
export function formatINR(n: number) { if (n >= 10000000) return `₹ ${(n / 10000000).toFixed(2)} Cr`; if (n >= 100000) return `₹ ${(n / 100000).toFixed(2)} L`; return `₹ ${n.toLocaleString('en-IN')}`; }
export const flagOf = (code: string) => code && code.length === 2 ? String.fromCodePoint(...[...code.toUpperCase()].map((c) => 127397 + c.charCodeAt(0))) : '';
export function formatMoney(n: number, cur: string) { if (cur === 'INR') return formatINR(n); try { return new Intl.NumberFormat('en', { style: 'currency', currency: cur, notation: n >= 1e6 ? 'compact' : 'standard', maximumFractionDigits: 2 }).format(n); } catch { return `${cur} ${n.toLocaleString()}`; } }
export const PROPERTY_COLS = 'id,ref,title,location,price,area_sqft,beds,baths,property_type,description,image,cover_url,gallery,amenities,featured,status,market,country,country_code,currency,price_in_inr,city,region,locality,categories(name)';
export type PropertyRow = { id: string; ref: string; title: string; location: string; price: number; area_sqft: number | null; beds: number | null; baths: number | null; property_type: string; description: string | null; image: string; cover_url?: string | null; gallery?: string[] | null; amenities: string[] | null; featured: boolean; status: string; market?: string; country?: string; country_code?: string; currency?: string; price_in_inr?: number | null; city?: string | null; region?: string | null; locality?: string | null; categories?: { name: string } | null };
export const coverOf = (r: { image: string; cover_url?: string | null }) => r.cover_url || propertyImages[r.image] || villa;
export function toListing(r: PropertyRow): Listing { return { id: r.ref, uuid: r.id, name: r.title, location: r.location, price: formatMoney(Number(r.price), r.currency ?? 'INR'), priceValue: Number(r.price_in_inr ?? r.price), category: r.categories?.name ?? 'Uncategorised', type: r.property_type, area: r.area_sqft ? `${r.area_sqft.toLocaleString('en-IN')} sq.ft` : '—', areaValue: r.area_sqft ?? 0, beds: r.beds ?? 0, baths: r.baths ?? 0, image: coverOf(r), gallery: r.gallery ?? [], description: r.description ?? '', amenities: r.amenities ?? [], featured: r.featured, status: r.status, market: r.market ?? 'india', country: r.country ?? 'India', countryCode: r.country_code ?? 'IN', currency: r.currency ?? 'INR', priceInr: r.price_in_inr ?? null, city: r.city ?? '', region: r.region ?? '' }; }
export const publicPages: Record<string, { title: string; eyebrow: string; description: string; sections: { title: string; body: string }[] }> = {
  about: { title: 'A more considered way to move.', eyebrow: 'ABOUT ELITEOZ', description: 'Eliteoz brings clarity, discretion and confidence to high-value real estate.', sections: [{ title: 'Built around trust', body: 'A curated marketplace designed to bring serious buyers and verified sellers together through a thoughtful, private experience.' }, { title: 'A higher standard', body: 'Identity, property information and membership are reviewed as part of the Eliteoz journey. Verification status is presented clearly at every step.' }] },
  'how-it-works': { title: 'A clear path to what’s next.', eyebrow: 'THE PROCESS', description: 'A considered experience from membership to meaningful connections.', sections: [{ title: '01 / Request private access', body: 'Choose a buyer or seller account and complete your personal information.' }, { title: '02 / Complete verification', body: 'Submit your information for review and follow your progress in your private workspace.' }, { title: '03 / Move with confidence', body: 'Explore verified opportunities or manage your listings, interests and viewing requests.' }] },
  buyers: { title: 'Exceptional places. A better way to find them.', eyebrow: 'FOR BUYERS', description: 'Discover a considered collection of high-value assets with clarity at every step.', sections: [{ title: 'Curated discovery', body: 'Search, save and compare opportunities suited to your ambitions.' }, { title: 'Private by design', body: 'Your interests and viewing requests stay organized in your own dedicated workspace.' }] },
  sellers: { title: 'Your property deserves the right audience.', eyebrow: 'FOR SELLERS', description: 'Present your property with confidence on a verification-led marketplace.', sections: [{ title: 'An elevated presentation', body: 'Create a complete listing with imagery, details and supporting documents.' }, { title: 'Manage every opportunity', body: 'Track property review, buyer interests, viewing requests and performance from one place.' }] },
  faq: { title: 'Questions, answered.', eyebrow: 'FREQUENTLY ASKED', description: 'A few things worth knowing before you begin.', sections: [{ title: 'Who can join Eliteoz?', body: 'Buyers and sellers can create an account and complete the required identity and membership steps.' }, { title: 'What does verification mean?', body: 'Eliteoz reviews submitted information and documents before marking an account or property as verified.' }, { title: 'Is my documentation visible to buyers?', body: 'No. Confidential KYC, bank and ownership documents are reserved for authorized review only.' }, { title: 'What is the activation fee?', body: 'The specification lists a ₹50,000 activation fee for buyers and sellers. Payment integration is not connected in this preview.' }] },
  contact: { title: 'Let’s start a conversation.', eyebrow: 'CONTACT', description: 'Questions about membership, a property or your account? Reach out to the Eliteoz team.', sections: [{ title: 'Membership enquiries', body: 'Use the enquiry form to tell us what you need. This frontend preview does not send messages yet.' }] },
  terms: { title: 'Terms & Conditions', eyebrow: 'POLICIES', description: 'Important information for using the Eliteoz platform.', sections: [{ title: 'Policy pending review', body: 'The final legal terms must be provided and approved by Eliteoz before launch. This page is a content placeholder, not legal advice.' }] },
  privacy: { title: 'Privacy Policy', eyebrow: 'POLICIES', description: 'How privacy is represented throughout the Eliteoz experience.', sections: [{ title: 'Private by design', body: 'Personal, identity and payment information is never shown in public property views. Final legal policy content must be supplied before launch.' }] },
  'payment-policy': { title: 'Payment Policy', eyebrow: 'POLICIES', description: 'Understand the membership activation journey.', sections: [{ title: 'Activation', body: 'The specified activation amount is ₹50,000. Gateway processing, refunds and legally binding payment terms require an approved integration and final policy text.' }] },
  'verification-policy': { title: 'Verification Policy', eyebrow: 'POLICIES', description: 'A transparent view of the verification process.', sections: [{ title: 'Review process', body: 'Submitted identity and property information is reviewed before an account or listing receives verified status. Final policy wording is pending approval.' }] },
  'seller-guidelines': { title: 'Seller Guidelines', eyebrow: 'RESOURCES', description: 'Present your property with accuracy and care.', sections: [{ title: 'A complete listing', body: 'Provide accurate specifications, clear imagery and the requested ownership information for authorized review.' }] },
  'buyer-guidelines': { title: 'Buyer Guidelines', eyebrow: 'RESOURCES', description: 'Explore opportunities thoughtfully.', sections: [{ title: 'A considered approach', body: 'Complete membership and verification, compare opportunities and use the interest and viewing tools to move forward.' }] },
};
