import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, BadgeCheck, Building2, Castle, Factory, Hotel, Landmark, MapPinned, ShieldCheck, Trees } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Footer, PropertyCard, PublicHeader, SectionHeading } from '@/components/eliteoz';
import { hero, properties } from '@/lib/eliteoz-data';
export const Route=createFileRoute('/')({head:()=>({meta:[{title:'ELITEOZ | Verified high-value real estate'},{name:'description',content:'Access real estate beyond the ordinary. Discover verified high-value properties and a considered membership experience.'},{property:'og:title',content:'ELITEOZ | Verified high-value real estate'},{property:'og:description',content:'Discover verified high-value properties and a considered membership experience.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Home});
const cats=[['Residential',Castle],['Commercial',Building2],['Land',Trees],['Industrial',Factory],['Hospitality',Hotel],['Investment',Landmark]] as const;
function Home(){return <><PublicHeader/><main><section className="hero"><img src={hero} alt="Contemporary luxury villa at dusk" width={1600} height={950}/><div className="container hero-content"><span className="eyebrow">A PRIVATE REAL ESTATE MARKETPLACE</span><h1>Access Real Estate<br/>Beyond the Ordinary</h1><p>A verified platform connecting serious buyers with high-value real estate opportunities.</p><div className="hero-actions"><Button size="lg" asChild><Link to="/register" search={{role:'buyer'}}>Register as Buyer <ArrowUpRight/></Link></Button><Link className="hero-ghost" to="/register" search={{role:'seller'}}>Register as Seller <ArrowRight size={16}/></Link><Link className="hero-ghost" to="/properties">Explore Properties <ArrowRight size={16}/></Link></div></div><span className="hero-foot">CURATED PROPERTIES · VERIFIED CONNECTIONS</span></section>
<section className="section container intro-grid"><div><span className="eyebrow">WELCOME TO ELITEOZ</span><h2>Real estate, handled with intention.</h2><p>Great opportunities deserve more than a crowded marketplace. Eliteoz brings together exceptional properties and purposeful people in a space designed for trust, discretion and clarity.</p><div className="intro-rule"/><div className="intro-facts"><div><strong>01</strong><span>Curated discovery</span></div><div><strong>02</strong><span>Verified access</span></div><div><strong>03</strong><span>Private connection</span></div></div></div><img className="intro-image" src={properties[0].image} alt="Contemporary villa surrounded by landscape" loading="lazy"/></section>
<section className="section section-alt"><div className="container"><SectionHeading eyebrow="THE COLLECTION" title="Properties worth exploring." description="Distinctive spaces selected for those looking for something beyond the expected." action={<Link className="text-link" to="/properties">Explore all properties <ArrowUpRight size={16}/></Link>}/><div className="property-grid">{properties.slice(0,3).map(p=><PropertyCard key={p.id} property={p}/>)}</div></div></section>
<section className="section container"><SectionHeading eyebrow="FIND YOUR PLACE" title="Explore by category."/><div className="category-grid">{cats.map(([name,Icon],i)=><Link to="/properties" search={{category:name}} key={name} className="category-tile"><Icon size={25} strokeWidth={1.2}/><div><span>0{i+1}</span><br/><strong>{name}</strong></div></Link>)}</div></section>
<section className="section section-alt"><div className="container"><SectionHeading eyebrow="THE ELITEOZ DIFFERENCE" title="Confidence in every connection."/><div className="feature-row"><article><span>01 /</span><h3>Thoughtfully curated</h3><p>Explore a considered collection of high-value properties without the noise of an ordinary portal.</p></article><article><span>02 /</span><h3>Verification-led</h3><p>Clear verification status creates a more transparent starting point for every opportunity.</p></article><article><span>03 /</span><h3>Built for privacy</h3><p>Private workspaces keep your enquiries, interests and property journey in one secure-feeling place.</p></article></div></div></section>
<section className="section container"><SectionHeading eyebrow="THE JOURNEY" title="Simple steps. Meaningful moves."/><div className="feature-row"><article><span>01</span><h3>Choose your path</h3><p>Join as a buyer or seller and create your dedicated account.</p></article><article><span>02</span><h3>Complete your profile</h3><p>Provide the required information for membership and identity review.</p></article><article><span>03</span><h3>Discover or list</h3><p>Explore opportunities or present your property to a focused audience.</p></article></div></section>
<section className="dark-band"><div className="container cta-grid"><div><span className="eyebrow">FOR BUYERS & SELLERS</span><h2>Different ambitions. One higher standard.</h2><p>Whether you are finding your next place or presenting your property, there is a place for you here.</p></div><div className="hero-actions"><Button variant="secondary" asChild><Link to="/buyers">For buyers <ArrowRight/></Link></Button><Button variant="outline" asChild><Link to="/sellers">For sellers <ArrowRight/></Link></Button></div></div></section>
<section className="section container"><SectionHeading eyebrow="TRUST & VERIFICATION" title="Care is part of the process." description="Identity and property checks are designed to make important decisions feel more informed."/><div className="feature-row"><article><ShieldCheck color="currentColor" size={28}/><h3>Member verification</h3><p>Follow each step of your review journey from your private dashboard.</p></article><article><BadgeCheck size={28}/><h3>Property review</h3><p>Clearly displayed property verification gives buyers context without exposing private documents.</p></article><article><MapPinned size={28}/><h3>Purposeful access</h3><p>Save, compare and request viewings through a thoughtful member experience.</p></article></div></section>
<section className="section section-alt"><div className="container"><SectionHeading eyebrow="GOOD TO KNOW" title="Your questions, considered."/><div className="content-sections"><article><h2>Who can join Eliteoz?</h2><p>Both buyers and sellers can register and follow the membership journey.</p></article><article><h2>Are documents visible publicly?</h2><p>No. Confidential identity, bank and ownership documents are not displayed to buyers.</p></article></div><Link className="text-link" to="/faq">More frequently asked questions <ArrowRight size={16}/></Link></div></section>
<section className="dark-band"><div className="container cta-grid"><div><span className="eyebrow">BEGIN WITH ELITEOZ</span><h2>Your next move deserves a better beginning.</h2></div><Button variant="secondary" asChild><Link to="/register">Become a member <ArrowUpRight/></Link></Button></div></section></main><Footer/></>}
