import { Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, BadgeCheck, Heart, MapPin, Menu, Search, ShieldCheck, X } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import type { Listing } from '@/lib/eliteoz-data';
import logo from '@/assets/eliteoz-logo.webp.asset.json';

export function Brand({ light = false }: { light?: boolean }) { return <Link to="/" className={`brand ${light ? 'brand-light' : ''}`} aria-label="Eliteoz home">ELITEOZ<span className="brand-dot">.</span></Link>; }
export function PublicHeader() {
 const [open,setOpen] = useState(false);
 const links = [['Properties','/properties'],['How it works','/how-it-works'],['For buyers','/buyers'],['For sellers','/sellers'],['About','/about'],['Contact','/contact']] as const;
 return <header className="public-header"><div className="header-inner"><Brand/><nav className="desktop-nav">{links.map(([label,path])=><Link key={path} to={path} activeProps={{className:'nav-active'}}>{label}</Link>)}</nav><div className="header-actions"><Button variant="ghost" asChild className="login-link"><Link to="/login">Log in</Link></Button><Button asChild><Link to="/register">Become a member <ArrowUpRight/></Link></Button></div><Button variant="ghost" size="icon" className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</Button></div>{open&&<nav className="mobile-nav">{links.map(([label,path])=><Link onClick={()=>setOpen(false)} key={path} to={path}>{label}</Link>)}<Link onClick={()=>setOpen(false)} to="/login">Log in</Link><Link onClick={()=>setOpen(false)} to="/register">Become a member</Link></nav>}</header>;
}
export function Footer(){const footerLinks=[['Properties','/properties'],['How It Works','/how-it-works'],['For Buyers','/buyers'],['For Sellers','/sellers'],['About','/about'],['Contact','/contact']] as const;return <footer className="nx-footer"><div className="nx-wrap nx-footer-grid"><div><img src={logo.url} alt="ELITEOZ" width={940} height={560} loading="lazy" className="nx-footer-logo" /><p className="nx-statement-line">Eliteoz — Where 50 Crore+ Assets Change Hands in Complete Silence.</p></div><nav>{footerLinks.map(([l,p])=><Link key={p} to={p}>{l}</Link>)}<Link to="/login">Login</Link><Link to="/register">Become a Member</Link></nav><div className="nx-footer-contact"><a href="mailto:privacy@eliteoz.com">privacy@eliteoz.com</a><a href="tel:+919315089933">9315089933</a></div></div><div className="nx-wrap nx-footer-bottom"><span>© 2026 ELITEOZ. All rights reserved.</span><span><Link to="/privacy">Privacy</Link> · <Link to="/terms">Terms</Link></span></div></footer>}
export function PageShell({children}:{children:React.ReactNode}){return <><PublicHeader/>{children}<Footer/></>}
export function PropertyCard({property, saved=false, onSave, onCompare, compared=false}:{property:Listing;saved?:boolean;onSave?:(id:string)=>void;onCompare?:(id:string)=>void;compared?:boolean}){return <article className="property-card"><div className="property-photo"><Link to="/properties/$id" params={{id:property.id}}><img src={property.image} alt={property.name} loading="lazy"/></Link><span className="verified-pill"><BadgeCheck size={13}/> ELITEOZ VERIFIED</span>{onSave&&<Button variant="outline" size="icon" className="save-property" aria-label={saved?'Remove saved property':'Save property'} onClick={()=>onSave?.(property.id)}><Heart size={17} fill={saved?'currentColor':'none'}/></Button>}</div><div className="property-info"><div className="property-type">{property.type} <span>•</span> {property.area}</div><Link to="/properties/$id" params={{id:property.id}} className="property-title">{property.name}</Link><div className="property-location"><MapPin size={14}/>{property.location}</div><div className="property-bottom"><strong>{property.price}</strong><Link to="/properties/$id" params={{id:property.id}} aria-label={`View ${property.name}`}><ArrowUpRight size={19}/></Link></div>{onCompare&&<Button variant="ghost" size="sm" className="compare-action" onClick={()=>onCompare(property.id)}>{compared?'✓ Added to compare':'+ Add to compare'}</Button>}</div></article>}
export function SearchBar({onSearch}:{onSearch?:(value:string)=>void}){const [text,setText]=useState('');return <form className="search-bar" onSubmit={e=>{e.preventDefault();onSearch?.(text)}}><Search size={19}/><input value={text} onChange={e=>setText(e.target.value)} placeholder="Search by location, property or keyword" aria-label="Search properties"/><Button type="submit">Search <ArrowRight size={16}/></Button></form>}
export function SectionHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:React.ReactNode}){return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>}
export function Notice({children}:{children:React.ReactNode}){return <div className="notice"><ShieldCheck size={18}/><span>{children}</span></div>}
