import { MarketBadge } from '@/components/market';
import { formatINR } from '@/lib/eliteoz-data';
import { Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, BadgeCheck, Heart, MapPin, Menu, Search, ShieldCheck, X } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import type { Listing } from '@/lib/eliteoz-data';
import logoSrc from '@/assets/eliteoz-logo.webp';
const logo = { url: logoSrc };

export function Brand({ light = false }: { light?: boolean }) { return <Link to="/" className={`brand ${light ? 'brand-light' : ''}`} aria-label="Eliteoz home">ELITEOZ<span className="brand-dot">.</span></Link>; }
const nav = [['Assets','/properties'],['How It Works','/how-it-works'],['For Buyers','/buyers'],['For Sellers','/sellers'],['About','/about'],['Contact','/contact']] as const;
export function PublicHeader() {
 const [open,setOpen] = useState(false);
 return <header className="nx-header"><div className="nx-wrap nx-header-row"><Link to="/" aria-label="Eliteoz home" className="nx-logo"><img src={logo.url} alt="ELITEOZ" width={940} height={560}/></Link><nav className="nx-nav">{nav.map(([l,p])=><Link key={p} to={p} activeProps={{className:'nx-nav-active'}}>{l}</Link>)}</nav><div className="nx-actions"><Link to="/login" className="nx-login">Log in</Link><button className="nx-burger" onClick={()=>setOpen(!open)} aria-label="Toggle menu" aria-expanded={open}>{open?<X size={22}/>:<Menu size={22}/>}</button></div></div>{open&&<nav className="nx-mobile-nav">{nav.map(([l,p])=><Link key={p} to={p} onClick={()=>setOpen(false)}>{l}</Link>)}<Link to="/login" onClick={()=>setOpen(false)}>Log in</Link></nav>}</header>;
}
export function Footer(){return <footer className="nx-footer"><div className="nx-wrap nx-footer-grid"><div><img src={logo.url} alt="ELITEOZ" width={940} height={560} loading="lazy" className="nx-footer-logo" /><p className="nx-statement-line">Eliteoz — Where INR 25 Cr. &amp; Above Assets Change Hands in Complete Silence.</p></div><nav>{nav.map(([l,p])=><Link key={p} to={p}>{l}</Link>)}<Link to="/login">Login</Link><Link to="/register">Private Access</Link></nav><div className="nx-footer-contact"><a href="mailto:Privacy@eliteoz.com">Privacy@eliteoz.com</a><a href="tel:+919315089933">+91 93150 89933</a><a href="tel:+918383935585">+91 83839 35585</a><span>14 School Lane, Barakhamba Avenue, Connaught Place, New Delhi — 110001</span></div></div><div className="nx-wrap nx-footer-bottom"><span>© 2026 ELITEOZ. All rights reserved.</span><span className="nx-legal-links"><Link to="/privacy">Privacy</Link> · <Link to="/terms">Terms</Link> · <Link to="/refund-policy">Refund</Link> · <Link to="/disclaimer">Disclaimer</Link> · <Link to="/cookie-policy">Cookies</Link></span></div></footer>}
export function PageShell({children}:{children:React.ReactNode}){return <><PublicHeader/>{children}<Footer/></>}
export function PropertyCard({property, saved=false, onSave, onCompare, compared=false}:{property:Listing;saved?:boolean;onSave?:(id:string)=>void;onCompare?:(id:string)=>void;compared?:boolean}){return <article className="property-card"><div className="property-photo"><Link to="/properties/$id" params={{id:property.id}}><img src={property.image} alt={property.name} loading="lazy"/></Link><span className="verified-pill"><BadgeCheck size={13}/> ELITEOZ VERIFIED</span><MarketBadge market={property.market} country={property.country} code={property.countryCode}/>{onSave&&<Button variant="outline" size="icon" className="save-property" aria-label={saved?'Remove saved property':'Save property'} onClick={()=>onSave?.(property.id)}><Heart size={17} fill={saved?'currentColor':'none'}/></Button>}</div><div className="property-info"><div className="property-type">{property.type} <span>•</span> {property.area}</div><Link to="/properties/$id" params={{id:property.id}} className="property-title">{property.name}</Link><div className="property-location"><MapPin size={14}/>{property.location}</div><div className="property-bottom"><strong>{property.price}{property.currency&&property.currency!=='INR'&&property.priceInr?<span className="price-sub">≈ {formatINR(property.priceInr)}</span>:null}</strong><Link to="/properties/$id" params={{id:property.id}} aria-label={`View ${property.name}`}><ArrowUpRight size={19}/></Link></div>{onCompare&&<Button variant="ghost" size="sm" className="compare-action" onClick={()=>onCompare(property.id)}>{compared?'✓ Added to compare':'+ Add to compare'}</Button>}</div></article>}
export function SearchBar({onSearch}:{onSearch?:(value:string)=>void}){const [text,setText]=useState('');return <form className="search-bar" onSubmit={e=>{e.preventDefault();onSearch?.(text)}}><Search size={19}/><input value={text} onChange={e=>setText(e.target.value)} placeholder="Search by location, property or keyword" aria-label="Search properties"/><Button type="submit">Search <ArrowRight size={16}/></Button></form>}
export function SectionHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:React.ReactNode}){return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>}
export function Notice({children}:{children:React.ReactNode}){return <div className="notice"><ShieldCheck size={18}/><span>{children}</span></div>}
