/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as BuyerGuidelinesRouteImport } from './routes/buyer-guidelines'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PaymentPolicyRouteImport } from './routes/payment-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellerGuidelinesRouteImport } from './routes/seller-guidelines'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerificationPolicyRouteImport } from './routes/verification-policy'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedActivateRouteImport } from './routes/_authenticated/activate'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBuyerRouteImport } from './routes/_authenticated/buyer'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSectionRouteImport } from './routes/_authenticated/admin.$section'
import { Route as AuthenticatedBuyerIndexRouteImport } from './routes/_authenticated/buyer.index'
import { Route as AuthenticatedBuyerSectionRouteImport } from './routes/_authenticated/buyer.$section'
import { Route as AuthenticatedSellerIndexRouteImport } from './routes/_authenticated/seller.index'
import { Route as AuthenticatedSellerSectionRouteImport } from './routes/_authenticated/seller.$section'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerGuidelinesRoute = BuyerGuidelinesRouteImport.update({
  id: '/buyer-guidelines',
  path: '/buyer-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPolicyRoute = PaymentPolicyRouteImport.update({
  id: '/payment-policy',
  path: '/payment-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerGuidelinesRoute = SellerGuidelinesRouteImport.update({
  id: '/seller-guidelines',
  path: '/seller-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationPolicyRoute = VerificationPolicyRouteImport.update({
  id: '/verification-policy',
  path: '/verification-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedActivateRoute = AuthenticatedActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyerRoute = AuthenticatedBuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSectionRoute =
  AuthenticatedAdminSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBuyerIndexRoute = AuthenticatedBuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedBuyerRoute,
} as any)
const AuthenticatedBuyerSectionRoute =
  AuthenticatedBuyerSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedBuyerRoute,
  } as any)
const AuthenticatedSellerIndexRoute =
  AuthenticatedSellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSectionRoute =
  AuthenticatedSellerSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-setup': typeof AdminSetupRoute
  '/buyer-guidelines': typeof BuyerGuidelinesRoute
  '/buyers': typeof BuyersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-guidelines': typeof SellerGuidelinesRoute
  '/sellers': typeof SellersRoute
  '/terms': typeof TermsRoute
  '/verification-policy': typeof VerificationPolicyRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activate': typeof AuthenticatedActivateRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/buyer': typeof AuthenticatedBuyerRouteWithChildren
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/buyer/$section': typeof AuthenticatedBuyerSectionRoute
  '/seller/$section': typeof AuthenticatedSellerSectionRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/buyer/': typeof AuthenticatedBuyerIndexRoute
  '/seller/': typeof AuthenticatedSellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-setup': typeof AdminSetupRoute
  '/buyer-guidelines': typeof BuyerGuidelinesRoute
  '/buyers': typeof BuyersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-guidelines': typeof SellerGuidelinesRoute
  '/sellers': typeof SellersRoute
  '/terms': typeof TermsRoute
  '/verification-policy': typeof VerificationPolicyRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activate': typeof AuthenticatedActivateRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties': typeof PropertiesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/buyer/$section': typeof AuthenticatedBuyerSectionRoute
  '/seller/$section': typeof AuthenticatedSellerSectionRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/buyer': typeof AuthenticatedBuyerIndexRoute
  '/seller': typeof AuthenticatedSellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-setup': typeof AdminSetupRoute
  '/buyer-guidelines': typeof BuyerGuidelinesRoute
  '/buyers': typeof BuyersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-guidelines': typeof SellerGuidelinesRoute
  '/sellers': typeof SellersRoute
  '/terms': typeof TermsRoute
  '/verification-policy': typeof VerificationPolicyRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/activate': typeof AuthenticatedActivateRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/buyer': typeof AuthenticatedBuyerRouteWithChildren
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/_authenticated/buyer/$section': typeof AuthenticatedBuyerSectionRoute
  '/_authenticated/seller/$section': typeof AuthenticatedSellerSectionRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/buyer/': typeof AuthenticatedBuyerIndexRoute
  '/_authenticated/seller/': typeof AuthenticatedSellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-setup'
    | '/buyer-guidelines'
    | '/buyers'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/mcp'
    | '/payment-policy'
    | '/privacy'
    | '/properties'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/seller-guidelines'
    | '/sellers'
    | '/terms'
    | '/verification-policy'
    | '/.well-known/oauth-protected-resource'
    | '/activate'
    | '/admin'
    | '/buyer'
    | '/seller'
    | '/properties/$id'
    | '/properties/'
    | '/.lovable/oauth/consent'
    | '/admin/$section'
    | '/buyer/$section'
    | '/seller/$section'
    | '/api/public/razorpay-webhook'
    | '/admin/'
    | '/buyer/'
    | '/seller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-setup'
    | '/buyer-guidelines'
    | '/buyers'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/mcp'
    | '/payment-policy'
    | '/privacy'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/seller-guidelines'
    | '/sellers'
    | '/terms'
    | '/verification-policy'
    | '/.well-known/oauth-protected-resource'
    | '/activate'
    | '/properties/$id'
    | '/properties'
    | '/.lovable/oauth/consent'
    | '/admin/$section'
    | '/buyer/$section'
    | '/seller/$section'
    | '/api/public/razorpay-webhook'
    | '/admin'
    | '/buyer'
    | '/seller'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin-setup'
    | '/buyer-guidelines'
    | '/buyers'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/mcp'
    | '/payment-policy'
    | '/privacy'
    | '/properties'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/seller-guidelines'
    | '/sellers'
    | '/terms'
    | '/verification-policy'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/activate'
    | '/_authenticated/admin'
    | '/_authenticated/buyer'
    | '/_authenticated/seller'
    | '/properties/$id'
    | '/properties/'
    | '/.lovable/oauth/consent'
    | '/_authenticated/admin/$section'
    | '/_authenticated/buyer/$section'
    | '/_authenticated/seller/$section'
    | '/api/public/razorpay-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/buyer/'
    | '/_authenticated/seller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminSetupRoute: typeof AdminSetupRoute
  BuyerGuidelinesRoute: typeof BuyerGuidelinesRoute
  BuyersRoute: typeof BuyersRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PaymentPolicyRoute: typeof PaymentPolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellerGuidelinesRoute: typeof SellerGuidelinesRoute
  SellersRoute: typeof SellersRoute
  TermsRoute: typeof TermsRoute
  VerificationPolicyRoute: typeof VerificationPolicyRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-guidelines': {
      id: '/buyer-guidelines'
      path: '/buyer-guidelines'
      fullPath: '/buyer-guidelines'
      preLoaderRoute: typeof BuyerGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-policy': {
      id: '/payment-policy'
      path: '/payment-policy'
      fullPath: '/payment-policy'
      preLoaderRoute: typeof PaymentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-guidelines': {
      id: '/seller-guidelines'
      path: '/seller-guidelines'
      fullPath: '/seller-guidelines'
      preLoaderRoute: typeof SellerGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-policy': {
      id: '/verification-policy'
      path: '/verification-policy'
      fullPath: '/verification-policy'
      preLoaderRoute: typeof VerificationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activate': {
      id: '/_authenticated/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof AuthenticatedActivateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer': {
      id: '/_authenticated/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof AuthenticatedBuyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$section': {
      id: '/_authenticated/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AuthenticatedAdminSectionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/buyer/': {
      id: '/_authenticated/buyer/'
      path: '/'
      fullPath: '/buyer/'
      preLoaderRoute: typeof AuthenticatedBuyerIndexRouteImport
      parentRoute: typeof AuthenticatedBuyerRoute
    }
    '/_authenticated/buyer/$section': {
      id: '/_authenticated/buyer/$section'
      path: '/$section'
      fullPath: '/buyer/$section'
      preLoaderRoute: typeof AuthenticatedBuyerSectionRouteImport
      parentRoute: typeof AuthenticatedBuyerRoute
    }
    '/_authenticated/seller/': {
      id: '/_authenticated/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof AuthenticatedSellerIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/$section': {
      id: '/_authenticated/seller/$section'
      path: '/$section'
      fullPath: '/seller/$section'
      preLoaderRoute: typeof AuthenticatedSellerSectionRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSectionRoute: typeof AuthenticatedAdminSectionRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSectionRoute: AuthenticatedAdminSectionRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBuyerRouteChildren {
  AuthenticatedBuyerSectionRoute: typeof AuthenticatedBuyerSectionRoute
  AuthenticatedBuyerIndexRoute: typeof AuthenticatedBuyerIndexRoute
}

const AuthenticatedBuyerRouteChildren: AuthenticatedBuyerRouteChildren = {
  AuthenticatedBuyerSectionRoute: AuthenticatedBuyerSectionRoute,
  AuthenticatedBuyerIndexRoute: AuthenticatedBuyerIndexRoute,
}

const AuthenticatedBuyerRouteWithChildren =
  AuthenticatedBuyerRoute._addFileChildren(AuthenticatedBuyerRouteChildren)

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerSectionRoute: typeof AuthenticatedSellerSectionRoute
  AuthenticatedSellerIndexRoute: typeof AuthenticatedSellerIndexRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerSectionRoute: AuthenticatedSellerSectionRoute,
  AuthenticatedSellerIndexRoute: AuthenticatedSellerIndexRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivateRoute: typeof AuthenticatedActivateRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBuyerRoute: typeof AuthenticatedBuyerRouteWithChildren
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivateRoute: AuthenticatedActivateRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBuyerRoute: AuthenticatedBuyerRouteWithChildren,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminSetupRoute: AdminSetupRoute,
  BuyerGuidelinesRoute: BuyerGuidelinesRoute,
  BuyersRoute: BuyersRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PaymentPolicyRoute: PaymentPolicyRoute,
  PrivacyRoute: PrivacyRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellerGuidelinesRoute: SellerGuidelinesRoute,
  SellersRoute: SellersRoute,
  TermsRoute: TermsRoute,
  VerificationPolicyRoute: VerificationPolicyRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
